# Generated by Django 2.2.15 on 2020-08-16 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(max_length=50)),
                ('subcourse1_comp', models.IntegerField(default=0)),
                ('subcourse2_comp', models.IntegerField(default=0)),
                ('subcourse3_comp', models.IntegerField(default=0)),
                ('subcourse4_comp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('sub_course_no', models.IntegerField()),
                ('video1', models.FileField(upload_to='videos/')),
                ('video2', models.FileField(upload_to='videos/')),
                ('video3', models.FileField(upload_to='videos/')),
                ('video4', models.FileField(upload_to='videos/')),
                ('transcript', models.FileField(upload_to='trans/')),
                ('quiz_marks', models.IntegerField()),
                ('mandatory', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
