# Generated by Django 2.2.15 on 2020-08-16 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcourse1_comp',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subcourse2_comp',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subcourse3_comp',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subcourse4_comp',
        ),
        migrations.RemoveField(
            model_name='subcourse',
            name='quiz_marks',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='lms/media/images/img03098-p1c4ja9s6v131m1ilh1bq8661273.jpg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('sub_course_no', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
